// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: M5mediaController

#ifndef _M5MEDIACONTROLLER_UI_H
#define _M5MEDIACONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void dropDownEntry_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Screen1_imgPlayPauseIcon(lv_event_t * e);
extern lv_obj_t * ui_Screen1_imgPlayPauseIcon;
void ui_event_Screen1_imgPreviousIcon(lv_event_t * e);
extern lv_obj_t * ui_Screen1_imgPreviousIcon;
void ui_event_Screen1_imgForwardIcon(lv_event_t * e);
extern lv_obj_t * ui_Screen1_imgForwardIcon;
void ui_event_Screen1_imgVolumeIcon(lv_event_t * e);
extern lv_obj_t * ui_Screen1_imgVolumeIcon;
void ui_event_Screen1_imgBrightnessIcon(lv_event_t * e);
extern lv_obj_t * ui_Screen1_imgBrightnessIcon;
void ui_event_Screen1_SliderVolume(lv_event_t * e);
extern lv_obj_t * ui_Screen1_SliderVolume;
void ui_event_Screen1_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_Screen1_SliderBrightness;
extern lv_obj_t * ui_Screen1_LabelVolume;
extern lv_obj_t * ui_Screen1_LabelBrightness;
extern lv_obj_t * ui_Screen1_playbackStatusBar;
extern lv_obj_t * ui_Screen1_currentPlayBackTime;
extern lv_obj_t * ui_Screen1_totalPlayBackTime1;
extern lv_obj_t * ui_Screen1_Image3;
extern lv_obj_t * ui_Screen1_LabelMusicTitle;
extern lv_obj_t * ui_Screen1_LabelArtistTitle;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_playpausebtn_png);    // assets/playPausebtn.png
LV_IMG_DECLARE(ui_img_bigpause_png);    // assets/bigPause.png
LV_IMG_DECLARE(ui_img_skip_previous_filled_png);    // assets/skip_previous_filled.png
LV_IMG_DECLARE(ui_img_1783407615);    // assets/skip_previous_filled-1.png
LV_IMG_DECLARE(ui_img_volume_2_png);    // assets/Volume 2.png
LV_IMG_DECLARE(ui_img_volume_x_png);    // assets/Volume x.png
LV_IMG_DECLARE(ui_img_light_mode_png);    // assets/light_mode.png
LV_IMG_DECLARE(ui_img_media_png);    // assets/Media.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
