// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: M5mediaController

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void playBtnClicked_callback(lv_event_t * e);
void pauseBtnClicked_callback(lv_event_t * e);
void backBtnClicked_callback(lv_event_t * e);
void forwardBtnClicked_callback(lv_event_t * e);
void mute_callback(lv_event_t * e);
void volLevelChanged_callback(lv_event_t * e);
void brightnessLvlChanged_callback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
