// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: M5mediaController

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x080808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Screen1, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Screen1, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_imgPlayPauseIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_imgPlayPauseIcon, &ui_img_playpausebtn_png);
    lv_obj_set_width(ui_Screen1_imgPlayPauseIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Screen1_imgPlayPauseIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Screen1_imgPlayPauseIcon, 132);
    lv_obj_set_y(ui_Screen1_imgPlayPauseIcon, 152);
    lv_obj_add_state(ui_Screen1_imgPlayPauseIcon, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_Screen1_imgPlayPauseIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_imgPlayPauseIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_imgPlayPauseIcon, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Screen1_imgPlayPauseIcon, lv_color_hex(0xDFDDDD), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Screen1_imgPlayPauseIcon, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Screen1_imgPlayPauseIcon, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Screen1_imgPlayPauseIcon, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_x(ui_Screen1_imgPlayPauseIcon, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_ofs_y(ui_Screen1_imgPlayPauseIcon, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_imgPreviousIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_imgPreviousIcon, &ui_img_skip_previous_filled_png);
    lv_obj_set_width(ui_Screen1_imgPreviousIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Screen1_imgPreviousIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Screen1_imgPreviousIcon, 60);
    lv_obj_set_y(ui_Screen1_imgPreviousIcon, 152);
    lv_obj_add_flag(ui_Screen1_imgPreviousIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_imgPreviousIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_imgPreviousIcon, 16, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Screen1_imgPreviousIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Screen1_imgPreviousIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Screen1_imgPreviousIcon, 16, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Screen1_imgPreviousIcon, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_Screen1_imgPreviousIcon, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Screen1_imgPreviousIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Screen1_imgPreviousIcon, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Screen1_imgPreviousIcon, 16, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Screen1_imgPreviousIcon, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_Screen1_imgPreviousIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Screen1_imgPreviousIcon, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_imgForwardIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_imgForwardIcon, &ui_img_1783407615);
    lv_obj_set_width(ui_Screen1_imgForwardIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Screen1_imgForwardIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Screen1_imgForwardIcon, 205);
    lv_obj_set_y(ui_Screen1_imgForwardIcon, 152);
    lv_obj_add_flag(ui_Screen1_imgForwardIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_imgForwardIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_imgForwardIcon, 16, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Screen1_imgForwardIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Screen1_imgForwardIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Screen1_imgForwardIcon, 16, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Screen1_imgForwardIcon, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_Screen1_imgForwardIcon, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Screen1_imgForwardIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Screen1_imgForwardIcon, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Screen1_imgForwardIcon, 16, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Screen1_imgForwardIcon, 1, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_Screen1_imgForwardIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Screen1_imgForwardIcon, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Screen1_imgVolumeIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_imgVolumeIcon, &ui_img_volume_2_png);
    lv_obj_set_width(ui_Screen1_imgVolumeIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Screen1_imgVolumeIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Screen1_imgVolumeIcon, 282);
    lv_obj_set_y(ui_Screen1_imgVolumeIcon, 168);
    lv_obj_add_flag(ui_Screen1_imgVolumeIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_imgVolumeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_imgBrightnessIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_imgBrightnessIcon, &ui_img_light_mode_png);
    lv_obj_set_width(ui_Screen1_imgBrightnessIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Screen1_imgBrightnessIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Screen1_imgBrightnessIcon, 10);
    lv_obj_set_y(ui_Screen1_imgBrightnessIcon, 168);
    lv_obj_add_flag(ui_Screen1_imgBrightnessIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Screen1_imgBrightnessIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_SliderVolume = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Screen1_SliderVolume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_SliderVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Screen1_SliderVolume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_SliderVolume, 10);
    lv_obj_set_height(ui_Screen1_SliderVolume, 122);
    lv_obj_set_x(ui_Screen1_SliderVolume, 287);
    lv_obj_set_y(ui_Screen1_SliderVolume, 27);
    lv_obj_add_flag(ui_Screen1_SliderVolume, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_SliderVolume, lv_color_hex(0x5AEE5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_SliderVolume, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_SliderVolume, lv_color_hex(0x5AEE5A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_SliderVolume, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_SliderVolume, lv_color_hex(0x5AEE5A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_SliderVolume, 100, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_SliderBrightness = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Screen1_SliderBrightness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Screen1_SliderBrightness, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_SliderBrightness, 10);
    lv_obj_set_height(ui_Screen1_SliderBrightness, 122);
    lv_obj_set_x(ui_Screen1_SliderBrightness, 17);
    lv_obj_set_y(ui_Screen1_SliderBrightness, 27);
    lv_obj_add_flag(ui_Screen1_SliderBrightness, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_SliderBrightness, lv_color_hex(0x5AEE5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_SliderBrightness, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_SliderBrightness, lv_color_hex(0x5AEE5A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_SliderBrightness, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_SliderBrightness, lv_color_hex(0x5AEE5A), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_SliderBrightness, 100, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_LabelVolume = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_LabelVolume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_LabelVolume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_LabelVolume, 281);
    lv_obj_set_y(ui_Screen1_LabelVolume, 3);
    lv_label_set_text(ui_Screen1_LabelVolume, "0");
    lv_obj_add_flag(ui_Screen1_LabelVolume, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen1_LabelVolume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_LabelVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1_LabelVolume, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_LabelBrightness = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_LabelBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_LabelBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_LabelBrightness, 10);
    lv_obj_set_y(ui_Screen1_LabelBrightness, 3);
    lv_label_set_text(ui_Screen1_LabelBrightness, "0");
    lv_obj_add_flag(ui_Screen1_LabelBrightness, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen1_LabelBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_LabelBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1_LabelBrightness, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_playbackStatusBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Screen1_playbackStatusBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Screen1_playbackStatusBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_playbackStatusBar, 312);
    lv_obj_set_height(ui_Screen1_playbackStatusBar, 8);
    lv_obj_set_x(ui_Screen1_playbackStatusBar, 4);
    lv_obj_set_y(ui_Screen1_playbackStatusBar, 225);
    lv_obj_set_style_bg_color(ui_Screen1_playbackStatusBar, lv_color_hex(0x365C32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_playbackStatusBar, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_playbackStatusBar, lv_color_hex(0x365C32), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_playbackStatusBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Screen1_currentPlayBackTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_currentPlayBackTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_currentPlayBackTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_currentPlayBackTime, 7);
    lv_obj_set_y(ui_Screen1_currentPlayBackTime, 206);
    lv_label_set_text(ui_Screen1_currentPlayBackTime, "01:37");
    lv_obj_set_style_text_color(ui_Screen1_currentPlayBackTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_currentPlayBackTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1_currentPlayBackTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_totalPlayBackTime1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_totalPlayBackTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_totalPlayBackTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_totalPlayBackTime1, 274);
    lv_obj_set_y(ui_Screen1_totalPlayBackTime1, 206);
    lv_label_set_text(ui_Screen1_totalPlayBackTime1, "04:20");
    lv_obj_set_style_text_color(ui_Screen1_totalPlayBackTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_totalPlayBackTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1_totalPlayBackTime1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Screen1_Image3, &ui_img_media_png);
    lv_obj_set_width(ui_Screen1_Image3, LV_SIZE_CONTENT);   /// 287
    lv_obj_set_height(ui_Screen1_Image3, LV_SIZE_CONTENT);    /// 155
    lv_obj_set_align(ui_Screen1_Image3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Screen1_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_LabelMusicTitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_LabelMusicTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_LabelMusicTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_LabelMusicTitle, 0);
    lv_obj_set_y(ui_Screen1_LabelMusicTitle, 108);
    lv_obj_set_align(ui_Screen1_LabelMusicTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Screen1_LabelMusicTitle, "Music Title");
    lv_obj_set_style_text_color(ui_Screen1_LabelMusicTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_LabelMusicTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1_LabelMusicTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_LabelMusicTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_LabelArtistTitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_LabelArtistTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_LabelArtistTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_LabelArtistTitle, 0);
    lv_obj_set_y(ui_Screen1_LabelArtistTitle, 124);
    lv_obj_set_align(ui_Screen1_LabelArtistTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Screen1_LabelArtistTitle, "Artist");
    lv_obj_set_style_text_color(ui_Screen1_LabelArtistTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_LabelArtistTitle, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen1_LabelArtistTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_LabelArtistTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1_imgPlayPauseIcon, ui_event_Screen1_imgPlayPauseIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_imgPreviousIcon, ui_event_Screen1_imgPreviousIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_imgForwardIcon, ui_event_Screen1_imgForwardIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_imgVolumeIcon, ui_event_Screen1_imgVolumeIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_imgBrightnessIcon, ui_event_Screen1_imgBrightnessIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_SliderVolume, ui_event_Screen1_SliderVolume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_SliderBrightness, ui_event_Screen1_SliderBrightness, LV_EVENT_ALL, NULL);

}
